# http接口测试框架配置信息

[private_debug]
# debug测试服务
tester = www
environment = debug
versionCode = testing
host = t.10jqka.com.cn
loginHost = upass.10jqka.com.cn/login?isIframe=1&main=3&pannel=1&source=sns&redir=https://t.10jqka.com.cn/static/loginBack.html
loginInfo = {
                "uname": "EUY6a0eRcQxbP31nZbr2rUl70/W6AgE0FhhBhJ8pxacl1dnjCpWbvCP5Ws9DqcQ/g4ej945ZO6NdRh0DW0RuHIEqYdFtjN11MKTB/i77XTe07Ckn28zMV2A9tXvUFk\
                         0/oU+UbcOZu9cahXUCavpTQ7CNT7HE8nPuGMW3/cQWbSU=",
                "passwd": "JvrxC9U7kMN6FUUW+XHbRPyJigJ+3riqp2sccGrGocR8rVcIhXuQIZ4CNY53BpaKSi4sEh4jGGqIKz0lM1lTQoS40Smnv9Isyl2AaRZbdPZ0Ig+g9oNIcDO6ekF\
                          r/s8hVSn+tk/OqRrmk7+5ClSBhDOs3PRuoP45fjm30OoJCAo="
            }

[online_release]
# release正式服务
tester = xiao xi
environment = release
versionCode = v1.0
host = docker-pre2
loginHost = docker-pre2/postLogin
loginInfo = {"email": 'wangjuan@user.com',"password": '123456',"auth": 'admin'}

[mail]
#发送邮件信息
smtpserver = smtp.qq.com
sender = 2524918238@qq.com
receiver = 2524918238@qq.com
username = 2524918238@qq.com
password = vfxzazounsjudjfj
